name: ml-unity
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9 # avoid exact patch/build version
  - pip
  - ca-certificates
  - libffi
  - openssl
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - numpy=1.21.2 # pin version used in pip deps, or you can move numpy to pip

  - pip:
      - protobuf==3.20.3
      - absl-py==2.2.2
      - astunparse==1.6.3
      - attrs==25.3.0
      - cattrs==1.5.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - deap==1.4.3
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.13.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - keras==3.10.0
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mlagents==0.30.0
      - mlagents-envs==0.30.0
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==25.0
      - pathspec==0.12.1
      - pettingzoo==1.15.0
